name: E2E
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build -- --configuration production
      - uses: cypress-io/github-action@v6
        with:
          start: npx http-server dist/cost-of-living-app -p 4200
          wait-on: 'http://localhost:4200'
